openapi: 3.0.3
info:
  title: Vector API
  description: API for vector operations
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /vector/insert:
    $ref: './paths/insert.yaml'
  /vector/bulk-insert:
    $ref: './paths/bulk-insert.yaml'
  /vector/search:
    $ref: './paths/search.yaml'

components:
  schemas:
    VectorComponent:
      $ref: './schemas/vectorComponent.yaml'
    VectorId:
      $ref: './schemas/vectorId.yaml'
