openapi: 3.0.3
info:
  title: Vector API
  description: API for inserting vectors into the system.
  version: 1.0.0
paths:
  /vector/insert:
    $ref: './endpoints/insert.yaml'

components:
  schemas:
    $ref: './components/components.yaml'